on:
  push:
  pull_request:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-python@v6.1.0
      - uses: pre-commit/action@v3.0.1

  test-stable:
    name: cargo test stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  check-msrv:
    name: cargo check msrv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: dtolnay/rust-toolchain@1.85
      - run: cargo check

  docs-stable:
    name: cargo doc stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc
